library(rix)
path_to_project <- "."
rix(r_ver = "latest", 
    r_pkgs = c(
      "devtools",
      "lattice", 
      "latticeExtra",
      "rmarkdown",
      "FITSio",
      "reshape2",
      "classInt",
      "imager",
      "fields",
      "latex2exp",
      "viridis",
      "rasterVis",
      "IDPmisc",
      "reticulate",
      "yaml",
      "gtools",
      "data.table",
      "spatstat",
      "colorspace",
      "ggplot2",
      "spam",
      "sp",
      "stringr",
      "rgl",
      "beepr",
      "codetools",
      "inlabru",
      "fmesher"),
    system_pkgs = c("glibc"),
    git_pkgs = list(package_name = "INLAutils",
                    repo_url = "https://github.com/timcdlucas/INLAutils.git",
                    branch_name = "master",
                    commit = "74d769a"),
    ide = "rstudio",
    project_path = path_to_project,
    overwrite = TRUE,
    print = FALSE)

